package com.wellnest.crm;

import com.getcapacitor.BridgeActivity;

// Standard Capacitor entry point — the WebView bridge, plugin
// registration (Local Notifications, Splash Screen, Background Runner),
// and lifecycle wiring are all handled by BridgeActivity + the plugins
// registered via capacitor.build.gradle (regenerated by `npx cap sync`).
// No custom native code needed for this app.
public class MainActivity extends BridgeActivity {
}
